######################################################################
# Automatically generated by qmake (3.0) ?? ???. 18 11:36:04 2016
######################################################################

TEMPLATE = app
TARGET = QtQuiz
INCLUDEPATH += .
QT+=widgets
# Input
HEADERS += answers.h window.h ../wordsStat.cpp
SOURCES += answers.cpp main.cpp window.cpp
